Repository GNU-CapstoneDesign-II/G-Learn-E-FE, pull requests merged in 2025-04, with the labels that each got.

#4 [Feat #3] 상단바, 메인화면, 로그인, 회원가입, 비밀번호 찾기 화면 구현
  src/App.jsx
  src/assets/hero-slogan.png
  src/assets/image-logo.png
  src/assets/logo.png
  src/assets/react.svg
  src/assets/sub-description.png
  src/assets/sub-slogan.png
  src/assets/text-logo.png
  src/components/Navbar.module.css
  src/components/Navbar.module.jsx
  src/index.css
  src/main.jsx
  src/pages/FindPassword.css
  src/pages/FindPassword.jsx
  src/pages/Login.css
  src/pages/Login.jsx
  src/pages/MainPage.css
  src/pages/MainPage.jsx
  src/pages/SignUp.css
  src/pages/SignUp.jsx
Labels: :sparkles: Feat

#9 fix/상단 바 위치 고정 및 수정을 위해 css 파일 수정
  src/components/Navbar.module.css
Labels: :hammer_and_wrench: Fix, 🔨 Refactor

#11 [Feat #5] 문제 생성 페이지 및 유형 설정 모달 구현
  index.html
  src/App.css
  src/App.jsx
  src/assets/G_Learn_E_Logo.png
  src/assets/G_Learn_E_Logo_ENG.png
  src/assets/image-logo-light.png
  src/assets/main_brown_eclipse.png
  src/components/Dropdown.jsx
  src/components/Dropdown.module.css
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Navbar.module.jsx
  src/components/home/SectionIntro.jsx
  src/components/home/SectionMain.jsx
  src/layouts/DefaultLayout.jsx
  src/layouts/SolveLayout.jsx
  src/main.jsx
  src/pages/ProblemGenerator.jsx
  src/pages/ProblemGenerator.module.css
  src/pages/home.jsx
Labels: :sparkles: Feat

#16 [Refactor #15] Tailwind 기반으로 전체 UI 스타일 재정비 및 공통 컴포넌트 적용
  package-lock.json
  package.json
  postcss.config.js
  src/components/Dropdown.jsx
  src/components/Dropdown.module.css
  src/components/SelectableButton.jsx
  src/index.css
  src/pages/ProblemGenerator.jsx
  src/pages/ProblemGenerator.module.css
  tailwind.config.js
Labels: 🔨 Refactor
