Repository GNU-CapstoneDesign-II/G-Learn-E-FE, pull requests merged in 2025-05, with the labels that each got.

#22 [Feat #21] 폴더링 시스템 도입 및 문제 생성 기능 개선
  package-lock.json
  package.json
  src/App.jsx
  src/api/Workbook.js
  src/api/axiosInstance.js
  src/api/privateFolderApi.js
  src/components/FolderListWithDnD.jsx
  src/components/LeftSideBar.module.css
  src/components/LeftSideBar.module.jsx
  src/components/Navbar.module.css
  src/components/Navbar.module.jsx
  src/components/UseInPages/Checkbox.module.css
  src/components/UseInPages/Checkbox.module.jsx
  src/components/UseInPages/PrivateHeader.module.css
  src/components/UseInPages/PrivateHeader.module.jsx
  src/components/cards/AddCard.module.css
  src/components/cards/AddCard.module.jsx
  src/components/cards/DocumentCard.module.css
  src/components/cards/DocumentCard.module.jsx
  src/components/cards/FolderCard.module.css
  src/components/cards/FolderCard.module.jsx
  src/components/common/FolderCreatePopup.jsx
  src/components/common/InformationPopup.jsx
  src/components/folder/PrivateMain.jsx
  src/components/folder/PrivateSidebar.jsx
  src/components/folder/PublicMain.jsx
  src/components/folder/PublicSidebar.jsx
  src/components/folder/TabSwitcher.jsx
  src/components/problem/ProblemNavbar.jsx
  src/contexts/AuthContext.jsx
  src/main.jsx
  src/pages/FolderPage.jsx
  src/pages/Login.jsx
  src/pages/Private.jsx
  src/pages/Private.module.css
  src/pages/ProblemGenerator.jsx
Labels: 🔨 Refactor, :sparkles: Feat

#28 [Feat #24] 메인화면 및 랭킹 페이지 구현, 주요 컴포넌트 스타일 개선
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/hero-slogan.png
  src/assets/image-logo-background.png
  src/assets/sub-description.png
  src/assets/sub-slogan.png
  src/components/Dropdown.jsx
  src/components/PdfUploadModal.jsx
  src/components/SelectableButton.jsx
  src/pages/MainPage.jsx
  src/pages/Ranking.jsx
  tailwind.config.js
Labels: 🔨 Refactor, :sparkles: Feat

#40 [Refactor #19] 문제 생성 컴포넌트 정리 및 UI 개선
  src/components/LeftSideBar.module.css
  src/components/LeftSideBar.module.jsx
  src/components/ProblemGenerator/Dropdown.jsx
  src/components/ProblemGenerator/FileUploadModal.jsx
  src/components/ProblemGenerator/SelectableButton.jsx
  src/components/UseInPages/Checkbox.module.css
  src/components/UseInPages/Checkbox.module.jsx
  src/components/UseInPages/PrivateHeader.module.css
  src/components/UseInPages/PrivateHeader.module.jsx
  src/components/cards/AddCard.module.css
  src/components/cards/AddCard.module.jsx
  src/components/cards/DocumentCard.module.css
  src/components/cards/DocumentCard.module.jsx
  src/components/cards/FolderCard.module.css
  src/components/cards/FolderCard.module.jsx
  src/components/common/InformationPopup.jsx
  src/pages/MainPage.jsx
  src/pages/Private.jsx
  src/pages/Private.module.css
  src/pages/ProblemGenerator.jsx
  src/pages/Ranking.jsx
Labels: 🔨 Refactor

#42 [Feat #41] 문제 풀이 보기 방식 전환 및 업로드 오류 해결
  package-lock.json
  package.json
  src/api/Workbook.js
  src/api/problemSolveApi.js
  src/api/workbookApi.js
  src/assets/grid-mode-icon.png
  src/assets/list-mode-icon.png
  src/components/common/UploadPopup.jsx
  src/components/problem/ProblemNavbar.jsx
  src/pages/FolderPage.jsx
  src/pages/ProblemGenerator.jsx
  src/pages/WorkbookSolve.jsx
Labels: 🔨 Refactor, :sparkles: Feat

#46 [Feat #43] 인증 API 연동 및 마이페이지 기능 개선
  src/App.jsx
  src/api/authApi.js
  src/api/axiosInstance.js
  src/api/userApi.js
  src/api/workbookApi.js
  src/assets/Level_Icon/level_0to10.png
  src/assets/Level_Icon/level_10to20.png
  src/assets/Level_Icon/level_20to30.png
  src/assets/Level_Icon/level_30to40.png
  src/assets/Level_Icon/level_40to50.png
  src/components/Navbar.jsx
  src/components/common/ConfirmModal.jsx
  src/components/common/LevelIcon.jsx
  src/components/folder/Checkbox.jsx
  src/components/folder/FolderListWithDnD.jsx
  src/components/folder/LeftSideBar.module.css
  src/components/folder/LeftSideBar.module.jsx
  src/components/folder/PrivateMain.jsx
  src/components/folder/PublicMain.jsx
  src/components/mypage/MyPageHome.jsx
  src/components/mypage/MyPageInfo.jsx
  src/contexts/AuthContext.jsx
  src/pages/FindPassword.jsx
  src/pages/MyPage.jsx
  src/pages/ProblemGenerator.jsx
  src/pages/SignUp.jsx
  src/utils/ProtectedRoute.jsx
  src/utils/PublicRoute.jsx
Labels: :sparkles: Feat

#53 [Feat #52] 업로드 문제집 수 추가
  src/components/mypage/MyPageHome.jsx
Labels: :sparkles: Feat

#66 [Feat #65] 유저 통계 페이지 및 시각화 컴포넌트 구현
  package-lock.json
  package.json
  src/App.jsx
  src/api/axiosInstance.js
  src/api/publicWorkbooksApi.js
  src/api/userApi.js
  src/api/workbookApi.js
  src/components/common/WorkbookProfilePopup.jsx
  src/components/folder/FolderListWithDnD.jsx
  src/components/folder/PublicMain.jsx
  src/components/mypage/BubbleChart.jsx
  src/components/mypage/HeatmapSVG.jsx
  src/components/mypage/MyPageInfo.jsx
  src/components/mypage/MyPageSidebar.jsx
  src/components/mypage/MyPageStatistics.jsx
  src/pages/KeywordRecommendPage.jsx
  src/pages/MyPage.jsx
  src/pages/SearchPage.jsx
Labels: :hammer_and_wrench: Fix, 🔨 Refactor, :sparkles: Feat

#68 [REFACTOR #67] Public 폴더 사이드바 동기화 및 학년 필터링 로직 개선
  package-lock.json
  src/api/axiosInstance.js
  src/components/folder/PublicMain.jsx
  src/pages/FolderPage.jsx
Labels: :hammer_and_wrench: Fix, 🔨 Refactor

#71 [FEAT #69] 회원 탈퇴 프론트 화면 구현
  src/components/mypage/MyPageWithdraw.jsx
  src/pages/MyPage.jsx
Labels: :sparkles: Feat

#73 [REFACTOR #72] 공개 폴더 페이지네이션 안정화 및 다중 다운로드 기능 추가
  src/api/publicFolderApi.js
  src/api/publicWorkbooksApi.js
  src/components/common/DownloadPopup.jsx
  src/components/folder/PublicMain.jsx
  src/pages/FolderPage.jsx
Labels: 🔨 Refactor, :sparkles: Feat

#75 [FEAT #74] 다운로드된 워크북에 업로드 아이콘 표시 및 다운로드 로직 구현
  package-lock.json
  src/components/folder/FolderListWithDnD.jsx
  src/components/folder/PublicMain.jsx
Labels: :sparkles: Feat

#76 [REFACTOR #70] SignUp.jsx에 비밀번호 최소 8자·영문+숫자 포함 제약 및 실시간 검증 로직 추가
  src/pages/SignUp.jsx
Labels: 🔨 Refactor, :sparkles: Feat

#80 [FIX #79] 여러 UI 요소의 디자인 디테일 개선 및 Ranking 페이지 오류 수정
  src/assets/download.png
  src/assets/profile.JPG
  src/components/Navbar.jsx
  src/components/folder/FolderListWithDnD.jsx
  src/components/folder/PublicMain.jsx
  src/components/mypage/BubbleChart.jsx
  src/components/mypage/MyPageHome.jsx
  src/components/mypage/MyPageSidebar.jsx
  src/pages/FolderPage.jsx
  src/pages/MainPage.jsx
  src/pages/Ranking.jsx
Labels: :hammer_and_wrench: Fix, 🔨 Refactor
